// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddPaths(arg1:Array<string>):Promise<app.ViewSnapshot>;

export function ChooseFiles():Promise<app.ViewSnapshot>;

export function ChooseFolder():Promise<app.ViewSnapshot>;

export function ClearQueue():Promise<app.ViewSnapshot>;

export function GetSnapshot():Promise<app.ViewSnapshot>;

export function Remove(arg1:Array<string>):Promise<app.ViewSnapshot>;

export function SetAllSelected(arg1:boolean):Promise<app.ViewSnapshot>;

export function SetSelected(arg1:string,arg2:boolean):Promise<app.ViewSnapshot>;

export function Start():Promise<app.ViewSnapshot>;

export function Stop():Promise<app.ViewSnapshot>;
