// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1) {
  return window['go']['main']['DesktopApp']['AddPaths'](arg1);
}

export function ChooseFiles() {
  return window['go']['main']['DesktopApp']['ChooseFiles']();
}

export function ChooseFolder() {
  return window['go']['main']['DesktopApp']['ChooseFolder']();
}

export function ClearQueue() {
  return window['go']['main']['DesktopApp']['ClearQueue']();
}

export function GetSnapshot() {
  return window['go']['main']['DesktopApp']['GetSnapshot']();
}

export function Remove(arg1) {
  return window['go']['main']['DesktopApp']['Remove'](arg1);
}

export function SetAllSelected(arg1) {
  return window['go']['main']['DesktopApp']['SetAllSelected'](arg1);
}

export function SetProfile(arg1) {
  return window['go']['main']['DesktopApp']['SetProfile'](arg1);
}

export function SetSelected(arg1, arg2) {
  return window['go']['main']['DesktopApp']['SetSelected'](arg1, arg2);
}

export function Start() {
  return window['go']['main']['DesktopApp']['Start']();
}

export function Stop() {
  return window['go']['main']['DesktopApp']['Stop']();
}
